### ISSUE TITLE
Закрытие первых двух этапов

### ISSUE THREAD

**Issue by BomGard** [jagermeisterteam/dergim_kurs_na_zbs#1]
- [x] Принятие задач заказчиком 1 этапа

- [x] Принятие задач заказчиком 2 этапа

**Comment by BomGard** [comment]
второй этап еще не закрыли :)

**Comment by VladimirBogopolskiy** [comment]
Точно, это я погорячился :)

**Comment by BomGard** [comment]
Тапни эксперта, нам второй этап за эту неделю нужно закрыть

**Comment by VladimirBogopolskiy** [comment]
> Тапни эксперта, нам второй этап за эту неделю нужно закрыть

Уже тапнул)
