### ISSUE TITLE
Обсудить печатные формы

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#10]
Обсудить с Алексеем вариант формирования печатных форм в ДО

**Comment by DmitriyLatysh** [comment]
Насколько я понял, Алексей сказал, что курим ПФ через ДО, но Литовка пару дней назад бахнул просто ВПФ. 
В чем смысловая нагрузка данного действия?

**Comment by VladimirBogopolskiy** [comment]
> Насколько я понял, Алексей сказал, что курим ПФ через ДО, но Литовка пару дней назад бахнул просто ВПФ.
> В чем смысловая нагрузка данного действия?

На данный момент, не смог расковырять ДО в плане формирования шаблонов ПФ.
На сегодня запланировал себе обсуждение с Алексеем, каким образом он видит реализацию данной задачи через ДО.

**Comment by DmitriyLatysh** [comment]
Лучший

**Comment by BomGard** [comment]
Вова, и сразу уточни про задачу Литовки. Может они быстрее курили и все им стало ясно. А нам забыли сказать

**Comment by VladimirBogopolskiy** [comment]
По результатам обсуждения с Алексеем было принято решение, что печатные формы :Договор подряда, Договор купли-продажи, Спецификация КП и Спецификация МО необходимо делать ВПФ.
Димон...крепись...
