### ISSUE TITLE
CMR им. Добкина

### ISSUE THREAD

**Issue by reidMaks** [jagermeisterteam/dergim_kurs_na_zbs#117]

**Comment by reidMaks** [comment]
[https://github.com/jagermeisterteam/Test_Obrobotki/raw/master/korobka_vpf/bin/%D0%9F%D0%B5%D1%87%D0%B0%D1%82%D1%8C%D0%9A%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%82%D0%B0.epf](url)

скачать тут и можно тестить

**Comment by VladimirBogopolskiy** [comment]
я бы поправил:

http://prntscr.com/nlun9y

**Comment by VladimirBogopolskiy** [comment]
http://prntscr.com/nnsd12

http://prntscr.com/nnsd8b
