### ISSUE TITLE
Консультационные работы по настройке УАТ СВ_Лодж

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#163]
- Обучение - 1 час

- Консультации 05.06 - 0.5 часа

- Консультации 14.06 - 2 часа

- Консультации .06 - 1 час

**Comment by BomGard** [comment]
Останавливаем до получения описанного БП

**Comment by VladimirBogopolskiy** [comment]
Принято
