### ISSUE TITLE
Синхронизация

### ISSUE THREAD

**Issue by BomGard** [jagermeisterteam/dergim_kurs_na_zbs#2]
- [x] настройка синхронизации

- [x] макет БП по загрузке выписок

- [x] описание дефицит   

- [x] Согласовать требования с бушкой! 

- [x] Доработка

- [x] Вернуть порядок заполнения пунктов маршрута в марш. лист

**Comment by reidMaks** [comment]
- тлэ не затаскивает сделку по платежному поручению входящему. Хотя БП ее отдает
- платежные поручения не проводятся и не взводится флаг Оплачено 
- счета на оплату не переносятся из БП как счета на оплату. только как Заказ на ТС

**Comment by VladimirBogopolskiy** [comment]
Беда

**Comment by reidMaks** [comment]
как имхо это будет работать: 
1. В тлэ создается РТУ и улетает в БП 
2. в БП можно создавать что душе угодно. Главное создать поступление на расчетный счет из банковской выписки и разнести его на конкретный РТУ. Дальше поступление на расчетный счет улетает в ТЛЭ
3. в ТЛЭ мы дорабатываем синхронизацию:
 - она привязывает сделку если поступление на расчетный счет разнесено на документ. 
 - автоматически проводит и ставит признак оплачено созданному платежному поручению входящему
 - на форму списка Заказа на ТС выносим флаг Оплачено. Смотрим на РТУ с Заказом в основании и   платежные поручения входящие. Если сумма оплат >= Суммы документа РТУ Тогда Оплачено = Истина

**Comment by reidMaks** [comment]
на 10 встреча

**Comment by reidMaks** [comment]
5165

**Comment by BomGard** [comment]
Ждем ее результатов

**Comment by VladimirBogopolskiy** [comment]
Результаты встречи:
1. Вариант реализации "Максима" она приняла, единственное, хочет проговорить со своими менеджерами, удобно ли им будет так определять оплату по ЭР
2. Договорились, что я оформлю задачу и отправлю ей на согласование

P.S. В ТЕНГЕ ОНИ НЕ ВЫСТАВЛЯЮТ СЧЕТА!

**Comment by reidMaks** [comment]
> 1. реализации "Максима"

патентую

**Comment by BomGard** [comment]
Требования согласованы, верно?

**Comment by VladimirBogopolskiy** [comment]
C бухгалтером да, она уточняет: " единственное, хочет проговорить со своими менеджерами, удобно ли им будет так определять оплату по ЭР"

**Comment by reidMaks** [comment]
Отдал доработки на суд товарища Тормунда

**Comment by VladimirBogopolskiy** [comment]
Тормунд доволен
