### ISSUE TITLE
Вопросы к обсуждению 22.03.2019

### ISSUE THREAD

**Issue by DmitriyLatysh** [jagermeisterteam/dergim_kurs_na_zbs#22]
1. Контактные лица Контрагента/Партнера для печатных форм.
_Комментарий:_ сейчас возможен только поиск Роли контактного лица по строке "Руководитель". Как искать Руководителя/Директора для печатных форм?

2. Банковские счета Организации.
_Комментарий:_ сейчас есть только список всех банковских счетов организации, нету признака основной банковский счет. Какой банковский счет подставлять в печатные формы?

3. Возможность сохранять печатные форм только в PDF. Прикреплять печатные формы в PDF в электронном письме.
_Комментарий:_ данный механизм необходимо сделать для всей системы или только для печатных форм/писем, которые открываются из Заказа клиента?

4. Печатная форма "Спецификация".
_Комментарий:_ Предоставлено 2 макета печатной формы "Спецификация". Есть подозрение, что второй макет относится к Калькуляциям.

5. Описание новой задачи по Резервам.

**Comment by VladimirBogopolskiy** [comment]
1. Останавливаемся на типовом справочнике "Роли контактных лиц". Создаем перечень ролей и используем только их.

2. Банковские счета, при указании в заказе клиента договора, указываются в самом документе "Договор" - реквизит "Счет покупателя". В случае, когда для взаиморасчетов не используются договора, необходимо уточнить у клиента.

3. Данный механизм необходимо сделать только для печ.форм Заказа клиента.

4. По одной ответ дал, по второй запросил комментарии у клиента.

5. Задача уходит на отдел Алексея.

**Comment by BomGard** [comment]
Вова, ответы получены на все вопросы?

**Comment by VladimirBogopolskiy** [comment]
> Вова, ответы получены на все вопросы?

Да
