### ISSUE TITLE
Ответить на письмо Пужайкиной

### ISSUE THREAD

**Issue by BomGard** [jagermeisterteam/dergim_kurs_na_zbs#24]
вопросы и уточнения по статусам

**Comment by VladimirBogopolskiy** [comment]
В работе

**Comment by VladimirBogopolskiy** [comment]
На письмо ответил.
Открытые вопросы вынес на обсуждение в четверг:
1. Проставление признака "Кредитный", в данный момент, не завязано на выборе договора в заказе клиента с типом договора "Кредитный". Попробуем предложить оставить возможность проставления признака кредитования заказа вручную для сотрудника с определенной ролью.
