### ISSUE TITLE
Данные в УТ(Кравченко Е.)

### ISSUE THREAD

**Issue by artemlavrik** [jagermeisterteam/dergim_kurs_na_zbs#260]

**Comment by BomGard** [comment]
Катя, писать свой механизм загрузки под УТ задача трудоемкая - 25 - 30 часов.
Можем предложить другой вариант:
1. Загружаем эти данные в БП
2. Настраиваем синхронизацию с УТ
3. Заливаем все, что позволит типовая синхронизация.
Плановая трудоемкость - 4 часа.
Риски: как всегда ошибки в данных после синхронизации.
