### ISSUE TITLE
МостСтройТранс оценка поступивших задач

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#279]
https://docs.google.com/document/d/1wngTvTzwqrpc9d7Ukl8EBJCJyh5cGcbaEv17WINh0WY/edit?usp=sharing

**Comment by BomGard** [comment]
Игорь сказал, что пока вопрос откладывается 
и непонятно на какой период 
будет держать нас в курсе
