### ISSUE TITLE
Задача №7

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#30]
Разработать механизм заполнения реквизита "Контрагент", документа "Экспедиторская расписка" данными реквизита "Клиент", документа взаимодействие. Заполнение производить при создании на основании.

**Comment by reidMaks** [comment]
репозиторий коробка перезалит. [https://github.com/jagermeisterteam/korobka_v1.git](url)

- [ ] нужно импортировать в EDT 

- [ ] создать **ветку dev_Vasya**

- [ ] Запушить изменения по задаче в **ветку dev_Vasya**

**Comment by VladimirBogopolskiy** [comment]
Затирается Контрагент при выборе Организации(поправить)
