### ISSUE TITLE
Печатная форма "Погрузочный лист"

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#31]
- [x] 1. Запросить информацию по составу данных печатной формы "Погрузочный лист"
- [ ] 2. Сделать оценку разработки печатной формы

**Comment by reidMaks** [comment]
когда разговор с клиентом ?

**Comment by VladimirBogopolskiy** [comment]
Договорились, что составлю файл, в котором выпишу все колонки. Потом свяжемся с ней и пройдемся по каждой колонке и определим от куда(в ТЛЭ) эти данные берутся.

**Comment by reidMaks** [comment]
для нас вроде срочности нет. в этот месяц печатку не закроем

> Вторая половина недели у них "плотная", так что ориентируемся на понедельник, но постараюсь выбить общение на этой неделе.

**Comment by BomGard** [comment]
> для нас вроде срочности нет. в этот месяц печатку не закроем

no money - no honey

**Comment by reidMaks** [comment]
foo 
bar

**Comment by reidMaks** [comment]
держи. поудаляю потом комменты
