### ISSUE TITLE
Конструктор

### ISSUE THREAD

**Issue by BomGard** [jagermeisterteam/dergim_kurs_na_zbs#4]

**Comment by reidMaks** [comment]
- [ 1. Предусмотреть механизм по разграничению количества товара, использованого для создания готового изделия при формировании элемента ТЧ "Товары" - "ГИ". Остачу количества номенклатуры, не попавшей в изготовление ГИ, записывать отдельными элементами.] 

- [2. Разработать механизм, позволяющий добавлять в ТЧ "Товары" заказ клиента виды номенклатуры в качестве номенклатуры. ] 

- [3. Добавить в группу "Тех.операции" реквизит "Вид операции". Реквизит находится в соответствующих группах каждой из вкладок "Конструктора калькуляций". В реквизите выводить список услуг, указанных в документе заказ клиента и отмеченных признаком "МО". В зависимости от выбранного вида операции проводить отбор по номенклатуре, входящей в его состав. ] 

- [ 4. Разработать механизм, осуществляющий проверку типа договора, выбранного в "Заказе клиента", при попытке сформировать калькуляцию с видом операции "Материал+Услуга" или "ГИ". В случае, когда по типу договора нельзя завести тот или иной вид операции, отказывать в открытии формы конструктора и выводить сообщение. По типу договора "С покупателем-поставщиком" 

Уточнение: 

4.1 В случае, когда в документе "Заказ клиента" выбран договор с типом сделки "Металл со склада+услуга" или "Услуги по переработке дав. сырья" перезаполнять ТЧ "Товары" после создания калькуляции по сценарию "Материал+Услуга".

4.2 В случае, когда в документе "Заказ клиента" выбран договор с типом сделки "ГИ из металла со склада" или "Услуги изготовления ГИ из дав. сырья" перезаполнять ТЧ "Товары" после создания калькуляции по сценарию "ГИ".

4.3 В случае, когда в документе "Заказ клиента" выбран договор с типом сделки "Металл со склада" или же взаиморасчеты ведутся без указания договора, скрывать на форме документа кнопки "Создать калькуляцию" и "Открыть калькуляцию".] 

- [ 5. Разработать механизм отображения всей номенклатуру заказа клиента, отмеченную признаком МО в документах раскроя, в реквизите исходной номенклатуры(Тип: Товар). Убрать кнопку "Добавить", оставить "Показать все". Отбор должен действовать в поле быстрого отбора.] 

- [6. Доработать форму списка документов Заказ клиента. На форму добавить дополнительную колонку "МО"(тип: Булево), заполнять в случае сформированной по заказу калькуляции. 

Уточнение: 

Поле названо "Калькуляции" т.к. на форме "ФормаСпискаДокументов" заказаКлиента есть поле "МО" ] 

- [7. Разработать механизм, контролирующий доступность товара, при добавлении его в калькуляции.  ] 

- [8. Разработать механизм, контролирующий следующую логику: если по товару, в рамках одной ветки ТЧ "Товары", не использована какая-то услуга, после создания калькуляции(нажатия на кнопку "обновить заказ", необходимо исключать ее из ТЧ с признаком МО. ] 

- [9. Разработать механизм, который выводит форму выбора определенного элемента ТЧ "Товары" в документах раскроя в случае выбора номенклатуры, по которой есть дублирующая ветка. ] 

- [ 10. Разработать механизм, актуализирующий цены и количество исходных товаров после нажития на кнопку "Обновить заказ" в конструкторе калькуляций.] 

- [11. Разработать механизм заполнения ТЧ вкладки "Полуфабрикаты", значениями выходных изделий, полученных в процессе создания документов на вкладке "Раскрой". ] 

- [12. Разработать механизм заполнения реквизитов группы "Материал", вкладки "Раскрой", из соответствующего документа данной вкладки. ] 

- [13. Разработать механизм, который собирает стоимость тех.операций и расходных материалов со всех вкладок конструктора по документу, выбранному на вкладке "Раскрой". Собирается в строке ТЧ "Товары" с видом номенклатуры ГИ.  ] 

- [14. В документ "Раскрой" добавить тип операции. Выводить данное значение в представление документа. Заполнять данные значения в колонку "Наименование" ТЧ "Калькуляции" каждого элемента. ] 

- [15. Разработать механизм, который отвечает за контроль заполнения вкладки "Упаковка". Заполнение данной вкладки является обязательным. В случае отсутствия упаковки, необходимо добавлять строку с наименование "Без упаковки" вручную. [Отменена] ] 

- [16. Разработать механизм, который делает доступной кнопку "Обновить заказ", в случае заполнения вкладки "Упаковка" ТЧ "Тех операции". До заполнения вкладки "Упаковка" ТЧ "Тех операции", кнопка "Обновить заказ" недоступна. ] 

- [17. Разработать механизм, автоматически заполняющий реквизиты "Количество"(вес) в пересчете от количества номенклатуры в штуках. ] 

- [ 18. Доработать форму документов раскроя. Добавить руппу "Тех.операции".
Состав реквизитов:
•Тех.операция
•Количество
•Цена
•Сумма]

**Comment by DmitriyLatysh** [comment]
Были такие задачи или сейчас уже есть?

1. Разработать процедуру автоматического присвоения признаку “Рассчитал”, типа Булево значения - Истина, после того, как была создана калькуляция(обновлен заказ клиента) на основании данного заказа.	
2. Доработать ТЧ на вкладке “Товары”. Добавить колонку “МО”. Данная колонка содержит реквизит “Булево”. Те позиции ТЧ у которых данный признак “Истина” являются элементами, по которым производится расчет услуг металлообработки при вызове “Конструктора калькуляций”.

Не знаю насколько они сейчас актуальны, нашел в своих письменах.

**Comment by reidMaks** [comment]
> Были такие задачи или сейчас уже есть?
> 
> 1. Разработать процедуру автоматического присвоения признаку “Рассчитал”, типа Булево значения - Истина, после того, как была создана калькуляция(обновлен заказ клиента) на основании данного заказа.
> 2. Доработать ТЧ на вкладке “Товары”. Добавить колонку “МО”. Данная колонка содержит реквизит “Булево”. Те позиции ТЧ у которых данный признак “Истина” являются элементами, по которым производится расчет услуг металлообработки при вызове “Конструктора калькуляций”.
> 
> Не знаю насколько они сейчас актуальны, нашел в своих письменах.

не. таких еще не видел

**Comment by reidMaks** [comment]
1. Создание объектной базы для функционирования и хранения данных Конструктора калькуляций
2. Разработка механизмов расчета и графического представления Раскроя металла
3. Разработка логики заполнения и контроль логической целостности данных Конструктора калькуляций
4. Разработка механизма расчета стоимости металлообработки. Консолидация результатов расчета  всех этапов металлообработки.
5. Разработка механизма обновления данных Заказа клиенту консолидированными данными стоимости металлообработки в зависимости от условий договора. Формирование документа Заказ на производство

**Comment by reidMaks** [comment]
>  14. В документ "Раскрой" добавить тип операции. Выводить данное значение в представление документа. Заполнять данные значения в колонку "Наименование" ТЧ "Калькуляции" каждого элемента. ]
У нас больше не будет раскроя Рулона?

**Comment by reidMaks** [comment]
1.  В Раскрое нет времени выполнения ТО. Добавлять или там другая логика переноса в форму калькулятора? 
2. Цены в калькуляторе фиксируются на какой-то момент? откуда их получать - из прайса или из стандартных объектов?

**Comment by reidMaks** [comment]
> 3. Добавить в группу "Тех.операции" реквизит "Вид операции"(тип: Справочник "Вид номенклатуры"). Реквизит находится в соответствующих группах каждой из вкладок "Конструктора калькуляций". В реквизите выводить список услуг, указанных в документе заказ клиента и отмеченных признаком "МО". В зависимости от выбранного вида операции проводить отбор по номенклатуре, входящей в его состав.

можем отказаться от этого требования за ненадобностью? реквизит выходит сугубо справочный, пользователь с ним взаимодействовать не будет ни как. Кроме того он должен быть связан с Тех операцией, на страницах где ТО это таб часть - не ясно с какой строкой связывать его значение.

**Comment by VladimirBogopolskiy** [comment]
> > 1. Добавить в группу "Тех.операции" реквизит "Вид операции"(тип: Справочник "Вид номенклатуры"). Реквизит находится в соответствующих группах каждой из вкладок "Конструктора калькуляций". В реквизите выводить список услуг, указанных в документе заказ клиента и отмеченных признаком "МО". В зависимости от выбранного вида операции проводить отбор по номенклатуре, входящей в его состав.
> 
> можем отказаться от этого требования за ненадобностью? реквизит выходит сугубо справочный, пользователь с ним взаимодействовать не будет ни как. Кроме того он должен быть связан с Тех операцией, на страницах где ТО это таб часть - не ясно с какой строкой связывать его значение.

После обсуждения с архитектором конструктора, было принято решение отказаться от разработки этого пункта.

**Comment by VladimirBogopolskiy** [comment]
> 1. В Раскрое нет времени выполнения ТО. Добавлять или там другая логика переноса в форму калькулятора?
> 2. Цены в калькуляторе фиксируются на какой-то момент? откуда их получать - из прайса или из стандартных объектов?

1. Предполагалось, что данный реквизит будет заполняться автоматически, как в УПП, но нужно обсудить данный момент с экспертами. В раскрой пока не добавлять.

2. Цены в калькуляторе фиксируются на момент создания калькуляции из прайса.

**Comment by reidMaks** [comment]
> Цены в калькуляторе фиксируются на момент создания калькуляции из прайса.

т.е  если я создал калькуляцию, а через неделю буду что-то в ней менять, цены должны быть актуальны на момент создания калькуляции? (грубо - момент внесения любых данных в форму калькуляции)

**Comment by reidMaks** [comment]
> > Цены в калькуляторе фиксируются на момент создания калькуляции из прайса.
> 
> т.е если я создал калькуляцию, а через неделю буду что-то в ней менять, цены должны быть актуальны на момент создания калькуляции? (грубо - момент внесения любых данных в форму калькуляции)

**уточнить у экспертов завтра**
