### ISSUE TITLE
Отработка вопросов по конструктору

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#48]
- [x] 1. Уточнить у экспертов, в какой момент должны актуализироваться цены на товары и услуги, используемые в конструкторе калькуляций(создания, обновление заказа клиента, изменение калькуляции с дальнейшим обновлением заказа клиента)

**Comment by VladimirBogopolskiy** [comment]
- [ ] 2 Обсудить: 
         2.1 В каждом виде номенклатуры тех.операций добавить обобщенную номенклатуру услуги с 
         приставкой "общ.".
         2.2 В обработке конструктор калькуляций, выводить только ту номенклатуру услуг, вид 
         номенклатуры которой указан номенклатуре "Общ." и отмечен признаком "МО".

- [ ] 7 Обсудить: Разработать механизм, контролирующий доступность товара, при добавлении его 
в калькуляции. В какой момент производится контроль доступности? Не относится ли это больше к процессу производства? 

- [ ] 9 Обсудить: Разработать механизм, который выводит форму выбора определенного элемента ТЧ "Товары" в документах раскроя в случае выбора номенклатуры, по которой есть дублирующая ветка. Подходит ли такой вариант реализации?

**Comment by reidMaks** [comment]
> 7 Обсудить: Разработать механизм, контролирующий доступность товара, при добавлении его
в калькуляции. В какой момент производится контроль доступности? Не относится ли это больше к процессу производства?

предлагаю ограничится доступностью кнопки создать калькуляцию в зависимости от типа обеспечения строк с МО = Истина
