### ISSUE TITLE
Доп. задачи 4.1 П1.2.\28

### ISSUE THREAD

**Issue by VladimirBogopolskiy** [jagermeisterteam/dergim_kurs_na_zbs#58]
- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5

**Comment by reidMaks** [comment]
по 1 и 2 дополнены новыми условиями видимости элементов
5 - состояние Кредитный не разработано. Задача к регламентному Установка статуса аннулирован ЗК
 - состояние документа на форме Кредитный
 
4 (аннулирован - создан) - ломает правила оплвты при переходе

6 отвязка платежа - найти платежку, удалить ссылку на документ и комментарий ?

**Comment by reidMaks** [comment]
реализация видимости команд печати после реализации ушла Димону с дополнениями

**Comment by reidMaks** [comment]
отвязка платежа ушла Дралю
