### ISSUE TITLE
коробка

### ISSUE THREAD

**Issue by reidMaks** [jagermeisterteam/dergim_kurs_na_zbs#59]
- [x] "Разработать механизм выбора валюты грузового места в ТЧ вкладки ""Грузовые места"".
Разработать выпадающий список предопределенных значений валют, разворачивающийся по нажатию на ячейку колонки ""Валюта""."

- [x] Разработать форму списка для хранения печатных форм CMR. Добавлять печатную форму в данную форму списка при печати ее из документов "Экспедиторская расписка" или "Маршрутный лист". Производить контроль добавления только одной экземпляра CMR для документов "Экспедиторская расписка"(также и в рамках Маршрутных листов). Использовать печать покомплектно, каждая ЭР - отдельный комплект. 
"Состав колонок формы списка:
1. Номер CMR
2. Грузоотправитель
3. Грузополучатель
Разместить форму списка доступной для вызова из подсистемы ""Логистика"", группы элементов ""Заказы на ТС""
Возможно хранить информацию об ЭР и МЛ, к которым относится печатная форма СMR. Файл печатной формы будет прикрепляться к документу ЭР(для каждой ЭР свой файл)."

- [x] Разработать печатную форму "Погрузочный лист". Форма доступна к печати из документов "Маршрутный лист". Также, доступна к печати из формы списка "Маршрутные листы". В случае множественного выбора документов "Маршрутный лист", печатная форма собирает в себе информацию по всем Экспедиторским распискам, входящим в состав маршрутного листа. 

- [x] "Настроить доступность вызова для печати, печатной формы CMR.
Печатная форма должна быть доступна только после заполнения реквизитов ТС и Водитель в документе ""Маршрутный лист"". "

- [x] Добавить возможность печати CMR из документов "Экспедиторская расписка" и формы списка этих документов.

**Comment by VladimirBogopolskiy** [comment]
3. Поправить печатную форму "Погрузочный лист".
В строке печатной формы, где указывается информация из маршрутного листа о ТС и водителе, выводить следующие денные:
    а. Номер маршрутного листа (реквизит маршрутного листа "Номер")
    b. Дата формирования маршрутного листа(реквизит маршрутного листа "от:") 
    c. Модель ТС (реквизит карточки ТС "Модель")
    d. Гос.номер ТС (реквизит карточки ТС "Гос.номер")
    e. Водитель (реквизит маршрутного листа "Водитель 1")
 [http://prntscr.com/nava13](url)

**Comment by reidMaks** [comment]
закинул все на прод. в т.ч МЛ для выдачи водителю
